version: '3'

services:
  chromedriver:
    image: robcherry/docker-chromedriver
    privileged: true
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=''

  selenium-side-runner:
    image: nixel2007/docker-selenium-side-runner
    build:
     context: .
    depends_on:
      - chromedriver
    volumes:
      - './sides:/sides'
      - './out:/root/out'
